[package]
name = "srt_subtitles_parser"
version = "0.1.0"
edition = "2024"
license = "MIT"
description = "A Rust-based parser that processes .srt (SubRip Subtitle) files and converts them into a structured data format"

[dependencies]
pest = "2.8.3"
pest_derive = "2.8.3"
